{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"12615693","self":"https://issues.apache.org/jira/rest/api/2/issue/12615693","key":"AMQ-4171","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12311210","id":"12311210","key":"AMQ","name":"ActiveMQ","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12311210&avatarId=10011","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12311210&avatarId=10011","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12311210&avatarId=10011","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12311210&avatarId=10011"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/11160","id":"11160","description":"ActiveMQ","name":"ActiveMQ"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12323282","id":"12323282","description":"Maintenance release with new AMQP support and smaller modules","name":"5.8.0","archived":false,"released":true,"releaseDate":"2013-02-11"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12312322":null,"customfield_12310220":"2012-11-13T15:15:16.919+0000","customfield_12312520":null,"customfield_12312323":null,"customfield_12312521":"Fri Dec 07 21:30:27 UTC 2012","customfield_12310420":"256998","customfield_12312320":null,"customfield_12310222":"1_*:*_1_*:*_2201799145_*|*_5_*:*_1_*:*_0","customfield_12312321":null,"resolutiondate":"2012-12-07T21:30:27.384+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312923":null,"customfield_12312326":null,"customfield_12312920":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312921":null,"customfield_12312324":null,"customfield_12312720":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/AMQ-4171/watchers","watchCount":2,"isWatching":false},"created":"2012-11-12T09:53:48.260+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.svg","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12313422":"false","customfield_12310310":"0.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12311120":null,"customfield_12312330":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12317974","id":"12317974","description":"Next v5 maintenance release","name":"5.6.0","archived":false,"released":true,"releaseDate":"2012-05-07"}],"issuelinks":[],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tabish121","name":"tabish121","key":"tabish121","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tabish121&avatarId=25249","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tabish121&avatarId=25249","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tabish121&avatarId=25249","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tabish121&avatarId=25249"},"displayName":"Timothy Bish","active":true,"timeZone":"America/Havana"},"customfield_12312337":null,"customfield_12312338":null,"updated":"2012-12-07T21:30:27.401+0000","customfield_12312335":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/5","description":"A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/resolved.png","name":"Resolved","id":"5","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12313892","id":"12313892","name":"Broker"}],"timeoriginalestimate":null,"customfield_12310080":null,"description":"On very fast test machines we got predictable FileNotFoundExceptions when a KahaDB data file was to be replaced by its successor.\n\nSee this from the log file:\n\n30.10.2012 21:00:56.359 [ActiveMQ Transport: tcp:///192.168.111.128:3134] [  ]  master-My-Company-S1-kellner20-vm Message ID:kellner20-vm-3125-1351618296390-23:1:1:2086:1 sent to queue://My-Company.dxm.request.provisionToTS\n30.10.2012 21:00:56.359 [BrokerService[master-My-Company-S1-kellner20-vm] Task-197] [  ]  My-Company.dxm.request.provisionToTS toPageIn: 1, Inflight: 0, pagedInMessages.size 0, enqueueCount: 2125, dequeueCount: 2124\n\n-------------------------------------------------------------------------------\n30.10.2012 21:00:56.390 [ConcurrentQueueStoreAndDispatch] [  ] *** SEVERE ***\nCalled from org.apache.activemq.store.kahadb.MessageDatabase.store()\n KahaDB failed to store to Journal\n-------------------------------------------------------------------------------\n\njava.io.FileNotFoundException: activemq-data\\master-My-Company-S1-kellner20-vm\\KahaDB\\db-2.log (The system cannot find the path specified)\n\tat java.io.RandomAccessFile.open(Native Method)\n\tat java.io.RandomAccessFile.<init>(Unknown Source)\n\tat org.apache.kahadb.journal.DataFile.openRandomAccessFile(DataFile.java:70)\n\tat org.apache.kahadb.journal.DataFileAppender.processQueue(DataFileAppender.java:309)\n\tat org.apache.kahadb.journal.DataFileAppender$1.run(DataFileAppender.java:188)\n\n30.10.2012 21:00:56.375 [BrokerService[master-My-Company-S1-kellner20-vm] Task-197] [  ]  org.apache.activemq.broker.region.cursors.QueueStorePrefetch@1afd356:My-Company.dxm.request.provisionToTS,batchResetNeeded=false,storeHasMessages=true,size=0,cacheEnabled=true - fillBatch\n30.10.2012 21:00:56.421 [ConcurrentQueueStoreAndDispatch] [  ] NOTIFICATION:  HighWater of SEVERE exceeded (value=1, highwater=1)!\n30.10.2012 21:00:56.437 [ConcurrentQueueStoreAndDispatch] [  ]  Stopping the broker due to IO exception, java.io.FileNotFoundException: activemq-data\\master-My-Company-S1-kellner20-vm\\KahaDB\\db-2.log (The system cannot find the path specified)\njava.io.FileNotFoundException: activemq-data\\master-My-Company-S1-kellner20-vm\\KahaDB\\db-2.log (The system cannot find the path specified)\n\tat java.io.RandomAccessFile.open(Native Method)\n\tat java.io.RandomAccessFile.<init>(Unknown Source)\n\tat org.apache.kahadb.journal.DataFile.openRandomAccessFile(DataFile.java:70)\n\tat org.apache.kahadb.journal.DataFileAppender.processQueue(DataFileAppender.java:309)\n\tat org.apache.kahadb.journal.DataFileAppender$1.run(DataFileAppender.java:188)\n\n********************\n(end of log file quotation)\n********************\n\nHaving evaluated all possibilities of the failure, we finally patched the following method of the class Journal::\n\n\nsynchronized DataFile rotateWriteFile() {\n        int nextNum = !dataFiles.isEmpty() ? dataFiles.getTail().getDataFileId().intValue() + 1 : 1;\n        File file = getFile(nextNum);\n        DataFile nextWriteFile = new DataFile(file, nextNum, preferedFileLength);\nPATCH START       try {\n   \t\t\tThread.sleep(10000);\n\t\t} catch (InterruptedException e) {\n\t\t\te.printStackTrace();\n\t\t}\nPATCH END\n        // actually allocate the disk space\n        fileMap.put(nextWriteFile.getDataFileId(), nextWriteFile);\n        fileByFileMap.put(file, nextWriteFile);\n        dataFiles.addLast(nextWriteFile);\n        return nextWriteFile;\n    }\n*************\n\nThis helped, the IO Exception never occurred again after this patch.\nIt seems that the \"nextWriteFile\"-object was  returned, while the allocating of the new Data File wasn't finished yet. \nAnyway, it is very strange that we should have detected this problem, and it never occurred earlier - at least no similar bug (???) seems to have been reported. Therefore, a critical examination of possibly deeper causes could be useful.\nBest regards, \nMatthias Vetter\nATOS, Frankfurt\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"attachment":[],"aggregatetimeestimate":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12312022":null,"customfield_12310041":null,"customfield_12310921":null,"customfield_12310920":"109146","customfield_12312823":null,"summary":"KahaDB / Journal rotateWriteFIle() sometimes too fast?","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":"Tested on Windows XP","customfield_12313520":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12615693/comment/13496244","id":"13496244","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tabish121","name":"tabish121","key":"tabish121","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tabish121&avatarId=25249","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tabish121&avatarId=25249","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tabish121&avatarId=25249","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tabish121&avatarId=25249"},"displayName":"Timothy Bish","active":true,"timeZone":"America/Havana"},"body":"This artificial delay is probably just masking some other issue as the allocation of the DataFile object doesn't actually cause a file to be created or read, only when DataFile.openRandomAccessFile is called is the file going to get created.  ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tabish121","name":"tabish121","key":"tabish121","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tabish121&avatarId=25249","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tabish121&avatarId=25249","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tabish121&avatarId=25249","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tabish121&avatarId=25249"},"displayName":"Timothy Bish","active":true,"timeZone":"America/Havana"},"created":"2012-11-13T15:15:16.919+0000","updated":"2012-11-13T15:15:16.919+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12615693/comment/13496252","id":"13496252","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"body":"Hi Timothy, \nyou are right, and I am sorry for having created an issue entry too early. Nevertheless, the delay really helped for some time. But today we detected an fileNotFound Exception inspite the delay, eventually. \nSo we have to keep on searching for the real problem..\nThanks! \n\nBest regards, \nMatthias Vetter\n\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"created":"2012-11-13T15:28:11.743+0000","updated":"2012-11-13T15:28:11.743+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12615693/comment/13503146","id":"13503146","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"body":"After deeper examination of the above described failure, we still have no solution to the problem:\nIt is always possible to create the first file db-1.log. But the creation of its successor always fails, always with the same exception: file not found, the system cannot find the path specified. \nThe DataFileAppender gets the next DataFile-object (from the method we suspected to be too fast) and then this DataFile object‘s method openRandomAccessFile is called. At this moment, the physical file is not yet existing, the RandomAccessFile-constructor called by the open-method is supposed to create the file. It did so, when db-1.log was created. The path to the files, naturally, wasn’t changed after that, and the same rights in the file system still are granted. \nThe only difference we see is, that now another file is already present and is about to be deleted. But should this have such an effect?\nWe also suspected the whitespaces in the absolute path to the file to be a problem – but why not in the first case with db-1.log?\nEven more irritating is that obviously no one else faced such kind of FileNotFound problem with the KahaDB. \nFinally, the problem seems to occur not on Windows 7, as initially reported, but on Windows XP. It also didn’t occur on a Solaris machine. \nPlease, has anyone an idea what could be going on here?  Any comment is welcome!!!!\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"created":"2012-11-23T10:31:44.192+0000","updated":"2012-11-23T10:34:23.476+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12615693/comment/13503866","id":"13503866","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tabish121","name":"tabish121","key":"tabish121","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tabish121&avatarId=25249","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tabish121&avatarId=25249","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tabish121&avatarId=25249","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tabish121&avatarId=25249"},"displayName":"Timothy Bish","active":true,"timeZone":"America/Havana"},"body":"Suggest moving to a later patch release of the JDK could be an issue there with Windows XP.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tabish121","name":"tabish121","key":"tabish121","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tabish121&avatarId=25249","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tabish121&avatarId=25249","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tabish121&avatarId=25249","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tabish121&avatarId=25249"},"displayName":"Timothy Bish","active":true,"timeZone":"America/Havana"},"created":"2012-11-26T16:21:28.217+0000","updated":"2012-11-26T16:21:28.217+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12615693/comment/13504729","id":"13504729","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"body":"In the meantime we found out, that all depends on the way we start our server, in which the broker is embedded. Using Windows (Win7 or xp, JDK 6 or 7 - all this doesn't matter), we can start the server either as a Windows service, using a .ini-file, from which jre/bin/server/jvm.dll is called, \neither manually using a .bat-file, calling java.exe. The jvm-parameters we pass are both times the same.\nStarting java.exe never leads to the described failures, starting with java.dll always. Needless to say, it stays a riddle how the start methods are related to the fileNotFound problem.\nAnyone experienced something like this?\nm.v.\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"created":"2012-11-27T16:27:34.351+0000","updated":"2012-11-27T16:27:34.351+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12615693/comment/13506465","id":"13506465","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"body":"Although it is strange that the file not found behaviour depends on the starting mode, there is a possibility to prevent the exception: \norg.apache.kahadb.journal.DataFile.openRandomAccessFile \ncalls: new RandomAccessFile(file, \"rw\");. Replacing this by\nnew RandomAccessFile(file.getCanonicalPath(), \"rw\"); helped!\n\nWhatever the deeper causes for the problem may be, the kahaDB would gain stability by opening RandomAccessFiles generally with os-proof pathnames rather than with file objects.\n\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mtmvetter","name":"mtmvetter","key":"mtmvetter","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Matthias Vetter","active":true,"timeZone":"Etc/UTC"},"created":"2012-11-29T13:22:45.765+0000","updated":"2012-11-29T13:22:45.765+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12615693/comment/13507405","id":"13507405","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tabish121","name":"tabish121","key":"tabish121","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tabish121&avatarId=25249","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tabish121&avatarId=25249","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tabish121&avatarId=25249","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tabish121&avatarId=25249"},"displayName":"Timothy Bish","active":true,"timeZone":"America/Havana"},"body":"The getCanonicalPath change makes sense and I've applied that on trunk, not sure what else can be done here. ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tabish121","name":"tabish121","key":"tabish121","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tabish121&avatarId=25249","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tabish121&avatarId=25249","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tabish121&avatarId=25249","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tabish121&avatarId=25249"},"displayName":"Timothy Bish","active":true,"timeZone":"America/Havana"},"created":"2012-11-30T16:16:51.114+0000","updated":"2012-11-30T16:16:51.114+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12615693/comment/13526785","id":"13526785","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tabish121","name":"tabish121","key":"tabish121","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tabish121&avatarId=25249","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tabish121&avatarId=25249","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tabish121&avatarId=25249","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tabish121&avatarId=25249"},"displayName":"Timothy Bish","active":true,"timeZone":"America/Havana"},"body":"The fix for the canonical file name use on open is in, not sure what else can be done here if anything.  The issue seems to be OS and JVM related not broker related. ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tabish121","name":"tabish121","key":"tabish121","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tabish121&avatarId=25249","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tabish121&avatarId=25249","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tabish121&avatarId=25249","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tabish121&avatarId=25249"},"displayName":"Timothy Bish","active":true,"timeZone":"America/Havana"},"created":"2012-12-07T21:30:27.399+0000","updated":"2012-12-07T21:30:27.399+0000"}],"maxResults":8,"total":8,"startAt":0},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/AMQ-4171/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i0j1bz:"}}